---
sidebar_position: 4
---

import RoutesOutput from '@site/src/components/ui/routes-output'

# exception handling

Certain errors within the Dream/Psychic ecosystem are automatically recognized by psychic, and handled with intuitive response codes automatically for you:

## castParam

In a controller, calling `this.castParam` with an invalid param passed will raise an exception which will cause Psychic to automatically raise a 400 error response, yielding an object with errors. In the following code, the call to `castParam` will raise a `400` unless the param for `id` is both passed, and a valid uuid.

```ts
import { OpenAPI } from '@rvoh/psychic'
import Place from '../../../models/Place.js'
import V1HostBaseController from './BaseController.js'

const openApiTags = ['places']

export default class V1HostPlacesController extends V1HostBaseController {
  @OpenAPI(Place, {
    status: 200,
    tags: openApiTags,
    description: 'Fetch a Place',
  })
  public async show() {
    const place = await this.currentHost
      .associationQuery('places')
      .preloadFor('default')
      .find(this.castParam('id', 'uuid'))
    this.ok(place)
  }
}
```

## paramsFor

Similar to `castParam`, `paramsFor` will raise a 400 exception if any of the params provided matching one of the model attributes is invalid.

```ts
export default class V1HostPlacesController extends V1HostBaseController {
  @OpenAPI(Place, {
    status: 201,
    tags: openApiTags,
    description: 'Create a Place',
  })
  public async create() {
    let place = await this.currentHost.createAssociation(
      'places',
      this.paramsFor(Place)
    )
    if (place.isPersisted) place = await place.loadFor('default').execute()
    this.created(place)
  }
}
```

## failable lookups

Certain methods in dream will cause a `RecordNotFound` exception to be thrown. If this exception is unhandled by your application code, it will automatically cause Psychic to raise a 404.

```ts
export default class V1HostPlacesController extends V1HostBaseController {
  @OpenAPI(Place, {
    status: 204,
    tags: openApiTags,
    description: 'Update a Place',
  })
  public async update() {
    const place = await this.place()
    // this will raise a 404 if no record is found
    await place.update(this.paramsFor(Place))
    this.noContent()
  }

  private async place() {
    return await this.currentHost
      .associationQuery('places')
      .findOrFail(this.castParam('id', 'string'))
  }
}
```

There are many failable lookup methods within dream, and taking advantage of them in your controllers can often save you an annoying manual step. Here are the other failable lookup methods that will case a 404 to be thrown:

- [firstOrFail](/docs/models/querying/firstOrFail)
- [lastOrFail](/docs/models/querying/lastOrFail)
- [findOrFail](/docs/models/querying/findOrFail)
- [findOrFailBy](/docs/models/querying/findOrFailBy)

## validation failures

Setting up [validations](/docs/models/validations/overview) on your models will automatically cause 422 errors to be thrown if any of the validations fails.
